---
# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: guestbook-application # +workload:namespace:type=string
spec:
  replicas: 3 # +workload:guestBookReplicas:default=3:type=int
  selector:
    matchLabels:
      app.kubernetes.io/app: guestbook
      app.kubernetes.io/tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/app: guestbook
        app.kubernetes.io/tier: frontend
    spec:
      containers:
        - name: php-redis
          image: gcr.io/google_samples/gb-frontend:v5 # +workload:guestBookImage:type=string
          env:
            - name: GET_HOSTS_FROM
              value: dns
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80 # +workload:guestBookContainerPort:default=80:type=int
