---
# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  labels:
    app.kubernetes.io/app: redis
    app.kubernetes.io/role: leader
    app.kubernetes.io/tier: backend
  namespace: guestbook-application # +workload:namespace:type=string
spec:
  ports:
    - port: 6379 # +workload:redisLeaderServicePort:default=6379:type=int
      targetPort: 6379 # +workload:redisLeaderContainerPort:default=6379:type=int
  selector:
    app.kubernetes.io/app: redis
    app.kubernetes.io/role: leader
    app.kubernetes.io/tier: backend
